services:
  db:
    image: postgres:13.4
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=twoops_tracker
      - POSTGRES_PASSWORD=twoops_tracker
      - POSTGRES_DB=twoops_tracker
    ports:
      # Allow DB access from outside the container
      - "54321:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twoops_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    image: codeforafrica/twoops_tracker:0.0.1
    restart: unless-stopped
    build:
      context: .
      target: python-app-ci
    volumes:
      - app-staticfiles:/app/staticfiles
      - ${APP_VOLUME:-app-files}:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - PGHOST=db
      - PGUSER=twoops_tracker
      - PGPASSWORD=twoops_tracker
      - PGDATABASE=twoops_tracker
    stdin_open: true
    tty: true
    command: ["/wait-for-postgres.sh", "/cmd.sh"]

  nginx:
    image: nginx:1.20.0
    restart: unless-stopped
    volumes:
      - ./contrib/docker-compose/nginx:/etc/nginx/conf.d
      - app-staticfiles:/var/www/static
      - app-mediafiles:/var/www/media
    ports:
      - 8000:80
    depends_on:
      - app

volumes:
  db-data:
  app-staticfiles:
  app-mediafiles:
  app-files:
